project:
  type: website
  output-dir: docs
  
website:
  title: "REPLICATION RESEARCH"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - submissions.qmd
      - review.qmd
      - Issues.qmd
      - collection.qmd
      - editorialteam.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/LukasRoeseler/replicationresearch_mockup
  page-footer:
    right: "Built with [Quarto](https://quarto.org/) and the [jtr13 website template](https://jtr13.github.io/website-template/)"
    left: "&copy; Copyright 2024, Lukas Röseler"

format:
  html:
    theme: Simplex
    toc: true
    grid:
      margin-width: 0px

editor: source

