project:
  type: website
  output-dir: docs
  
website:
  title: "REPLICATION RESEARCH"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - submissions.qmd
      - review.qmd
      - Issues.qmd
      - collection.qmd
      - editorialteam.qmd
    tools:
      - icon: github
        href: https://github.com/LukasRoeseler/replicationresearch_mockup
  page-footer:
    right: "Built with [Quarto](https://quarto.org/) and the [jtr13 website template](https://jtr13.github.io/website-template/)"
    left: "Shared under a CC-By Attribution 4.0 International license. Cite as Röseler, L. (2024, August 13). StaRT Reports. https://doi.org/10.17605/OSF.IO/BRXTD"

format:
  html:
    theme: Simplex
    toc: true
    grid:
      margin-width: 0px

editor: source

