project:
  type: website
  output-dir: docs
  
website:
  title: ""
  
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**WARNING** This website is in development. Submissions are not open yet and all content is subject to change. If you have feedback, please get in touch with lukas.roeseler[at]uni-muenster.de."
    type: primary
    position: below-navbar
  
  navbar:
    logo: img/rr_blue.jpg
    left:
      - href: index.qmd
        text: R2
      - href: symposium.qmd
        text: Symposium
      - about.qmd
      - submissions.qmd
      - review.qmd
      - Issues.qmd
      - editorialteam.qmd
    tools:
      - icon: github
        href: https://github.com/LukasRoeseler/replicationresearch_mockup
  page-footer:
    right: "Built with [Quarto](https://quarto.org/) and the [jtr13 website template](https://jtr13.github.io/website-template/)"
    left: "Shared under a CC-By Attribution 4.0 International license. Cite as Röseler, L. (2024, August 13). StaRT Reports. https://doi.org/10.17605/OSF.IO/BRXTD"

format:
  html:
    theme: Simplex
    toc: true
    page-layout: full
    grid:
      margin-width: 0px

editor: source

